CREATE TABLE usuarios (
    codigo_de_pessoa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    telefone VARCHAR(30),
    login VARCHAR(80) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_usuario_login UNIQUE (login)
);

CREATE TABLE alunos (
    codigo_de_pessoa BIGINT PRIMARY KEY REFERENCES usuarios(codigo_de_pessoa),
    data_ingresso DATE NOT NULL,
    situacao_academica VARCHAR(40) NOT NULL
);

CREATE TABLE professores (
    codigo_de_pessoa BIGINT PRIMARY KEY REFERENCES usuarios(codigo_de_pessoa),
    titulacao VARCHAR(100) NOT NULL,
    area_atuacao VARCHAR(150) NOT NULL,
    data_admissao DATE NOT NULL
);

CREATE TABLE secretarias (
    codigo_de_pessoa BIGINT PRIMARY KEY REFERENCES usuarios(codigo_de_pessoa),
    setor VARCHAR(100) NOT NULL,
    cargo VARCHAR(100) NOT NULL
);

CREATE TABLE cursos (
    codigo VARCHAR(30) PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    total_creditos INTEGER NOT NULL CHECK (total_creditos > 0)
);

CREATE TABLE disciplinas (
    codigo VARCHAR(30) PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    creditos INTEGER NOT NULL CHECK (creditos > 0)
);

CREATE TABLE curso_disciplinas (
    curso_codigo VARCHAR(30) NOT NULL REFERENCES cursos(codigo),
    disciplina_codigo VARCHAR(30) NOT NULL REFERENCES disciplinas(codigo),
    PRIMARY KEY (curso_codigo, disciplina_codigo)
);

CREATE TABLE turmas (
    codigo VARCHAR(30) PRIMARY KEY,
    semestre VARCHAR(6) NOT NULL,
    inicio_matriculas DATE NOT NULL,
    fim_matriculas DATE NOT NULL,
    situacao VARCHAR(30) NOT NULL,
    disciplina_codigo VARCHAR(30) NOT NULL REFERENCES disciplinas(codigo),
    professor_id BIGINT NOT NULL REFERENCES professores(codigo_de_pessoa),
    CONSTRAINT ck_periodo_matriculas CHECK (fim_matriculas >= inicio_matriculas)
);

CREATE TABLE matriculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    optativa BOOLEAN NOT NULL,
    situacao VARCHAR(30) NOT NULL,
    aluno_id BIGINT NOT NULL REFERENCES alunos(codigo_de_pessoa),
    turma_codigo VARCHAR(30) NOT NULL REFERENCES turmas(codigo),
    CONSTRAINT uk_matricula_aluno_turma UNIQUE (aluno_id, turma_codigo)
);

CREATE INDEX idx_turma_professor ON turmas(professor_id);
CREATE INDEX idx_turma_disciplina_semestre ON turmas(disciplina_codigo, semestre);
CREATE INDEX idx_matricula_turma ON matriculas(turma_codigo);
CREATE INDEX idx_curso_disciplina ON curso_disciplinas(disciplina_codigo);
